project:
  type: website
  output-dir: docs

website:
  google-analytics: G-YRV1CTB1QL
  title: Data Hub
  site-url: https://sites.bu.edu/CHDS-data-hub/
  repo-url: https://github.com/cmilando/CHDS_bookdown
  repo-branch: main
  repo-actions: [edit]
  page-footer: CHDS Data Hub - [https://sites.bu.edu/CHDS-data-hub/](https://sites.bu.edu/CHDS-data-hub/){target="_blank"}

  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Internal Data
        file: data_sources.qmd
      - text: External Data
        file: data_external.qmd
      - text: Research Environments
        file: data_infrastructure.qmd
      - text: Staff
        file: staff.qmd

format:
  html:
    theme:
      - cosmo
      - markdown-style.scss

bibliography: references.bib
csl: nature.csl
